### PR TITLE
Added Uzbek language

### PR DESCRIPTION
**Pull request by vodiylik**
I'm translated theme texts into Uzbek language

### CODE REVIEW

**Comment by godofredoninja** [comment]
🤓  Hello @vodiylik 

Thank you for the effort you are making to collaborate with Simply.

Please could you update it with the new version of the Simply Theme.

**Comment by vodiylik** [comment]
Hello @godofredoninja updated

**Comment by godofredoninja** [comment]
Hi

Great. Now you can update the translation of `uz.json`

When you finish updating the translation send it back to me to merge with the main branch. 

🤓

**Comment by vodiylik** [comment]
Hello @godofredoninja. Translated all new strings

**Comment by godofredoninja** [comment]
🤓  Hi @vodiylik 

Excellent, you've done a good job. Right now I will merge with the main branch.

**Pull request merged**
