### PR TITLE
Added native comments Post.hbs

### PR DESCRIPTION
**Pull request by thimiraonline**

### CODE REVIEW

**Comment by alexgallacher** [comment]
Hey @thimiraonline,

I've tried this commit and I don't get comments - I take it this is working on your site?

Alex.

**Comment by thimiraonline** [comment]
Yes. You have to update Ghost to 5.9.4. My website is https://androidwedakarayo.com

**Comment by alexgallacher** [comment]
Site looks great - i've updated with a copy/paste of your commit in the article-comments.hbs (see attached) and no luck... My website is alexgallacher.com and running on 5.9.4 - any thoughts?

[simply-0.4.0_comments2.zip](https://github.com/godofredoninja/simply/files/9363450/simply-0.4.0_comments2.zip)

**Comment by thimiraonline** [comment]
Did you enable the comments through the Admin panel.

**Comment by alexgallacher** [comment]
> Did you enable the comments through the Admin panel. 

Ah that'll do it - didn't realise I had to update that! Thanks! Alex

**Comment by thimiraonline** [comment]
Did it work?

**Comment by alexgallacher** [comment]
> I just checked your website and found that you have added the comments to the wrong place. image

Hey, Sorry I had a few other things on so I dropped off the radar for a bit. Yeah very strange - this is using your simply-patch-2.zip as the theme after enabling the comments section under membership - not sure why this is the case...

**Comment by thimiraonline** [comment]
Share your theme repo, I will add it to the right place and make a PR.

**Comment by thimiraonline** [comment]
> Hey

Share your theme repo. I will add it to the right place and make a PR.

**Pull request merged**
